[package]
name = "libgit-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "gitpub"
rust-version = "1.63"

[lib]
path = "src/lib.rs"

[dependencies]
libz-sys = "1.1.19"

[build-dependencies]
autocfg = "1.4.0"
make-cmd = "0.1.0"
